name: Test

on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.deployment.ref }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Find git
        run: |
          echo "Path env var: $PATH"
          echo "whereis command result:"
          whereis git
          echo "Git version"
          git --version

      - name: Run Go script test
        run: go run test.go

      - name: Installed Kustomize version
        run: |
          kustomize version
          whereis kustomize

      - name: Remove existing kustomize and install it again
        run: |
          sudo rm /snap/bin/kustomize
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv ./kustomize /usr/local/bin
          whereis kustomize

      - name: Run kustomize build
        run: kustomize build ./k8s
